#!/bin/bash
# Quick diagnostic script to check if Ghost automation is working
# Run this to see if 6 AM prophecy triggered

echo "============================================================"
echo "🔍 GHOST 6 AM AUTOMATION CHECK"
echo "============================================================"
echo "Date: $(date)"
echo ""

echo "📋 CHECKLIST:"
echo ""
echo "1️⃣  Did you receive a Telegram message at 6 AM today (Dec 19)?"
echo "   [ ] YES - Prophecy arrived"
echo "   [ ] NO - Automation didn't trigger"
echo ""

echo "2️⃣  Check Railway logs for Dec 19, 6:00-6:15 AM:"
echo ""
echo "   Go to: Railway Dashboard → ghost-protocol → Deployments"
echo "   Click: 'View Logs'"
echo "   Filter: Dec 19, 2025, 06:00 - 06:15"
echo ""
echo "   Look for these keywords:"
echo "     • 'prophecy'"
echo "     • 'oracle'"
echo "     • 'morning'"
echo "     • 'scheduler'"
echo "     • 'APScheduler'"
echo "     • 'daily_top_10'"
echo ""

echo "3️⃣  Check for manual trigger availability:"
echo ""
echo "   Try: curl -X POST https://ghost-protocol-production.up.railway.app/api/demo/morning_now"
echo ""

echo "============================================================"
echo "🔧 TROUBLESHOOTING"
echo "============================================================"
echo ""

echo "If NO prophecy at 6 AM:"
echo ""
echo "  ❌ Problem: APScheduler not running in Railway"
echo ""
echo "  ✅ Solutions:"
echo "     1. Check if scheduler is disabled by env var"
echo "     2. Verify wolf_app.py starts scheduler on boot"
echo "     3. Check if Railway is killing idle processes"
echo "     4. May need to add scheduler to Procfile"
echo ""

echo "If MANUAL trigger works but AUTO doesn't:"
echo ""
echo "  ❌ Problem: Scheduler not configured in production"
echo ""
echo "  ✅ Solution: Need to enable background scheduler"
echo ""

echo "============================================================"
echo "📊 NEXT STEPS"
echo "============================================================"
echo ""
echo "1. Answer the Telegram question above"
echo "2. Share Railway logs from 6:00-6:15 AM Dec 19"
echo "3. We'll diagnose the exact issue"
echo ""
echo "If automation failed, we can:"
echo "  • Trigger prophecy manually right now"
echo "  • Fix scheduler for tomorrow (Dec 20)"
echo "  • Still test all 6 fixes with manual trigger"
echo ""

echo "Run this to manually trigger prophecy NOW:"
echo ""
echo "  curl -X POST https://ghost-protocol-production.up.railway.app/api/demo/morning_now \\"
echo "    -H 'Content-Type: application/json'"
echo ""
echo "============================================================"
