#!/bin/bash
# PHASE 5 MILESTONE 1 - DEPLOYMENT GUIDE
# =======================================
# Deploy autonomous execution to Railway

echo "🚀 PHASE 5 MILESTONE 1 - DEPLOYMENT GUIDE"
echo "=========================================="
echo ""

echo "📋 PRE-DEPLOYMENT CHECKLIST"
echo "----------------------------"
echo "✅ Task 1.1: autonomous_execution_engine.py created (560 lines)"
echo "✅ Task 1.2: trade_decision_engine.py created (382 lines)"
echo "✅ Task 1.3: sl_tp_monitor.py enhanced (trailing stops, expiry)"
echo "✅ Task 1.4: wolf_app.py Stage 5 integration added"
echo "✅ Task 1.5: telegram_hunter.py trade notifications added"
echo "✅ Task 1.6: test_autonomous_execution.py created"
echo ""

echo "🧪 STEP 1: RUN TESTS LOCALLY"
echo "----------------------------"
echo "Run the test suite to validate Phase 5 components:"
echo ""
echo "  python3 test_autonomous_execution.py"
echo ""
echo "All tests should pass before deployment."
echo ""
read -p "Press Enter when tests pass..."
echo ""

echo "🔧 STEP 2: CONFIGURE RAILWAY ENVIRONMENT VARIABLES"
echo "--------------------------------------------------"
echo "Add these variables to Railway dashboard:"
echo ""
echo "# Phase 5: Autonomous Execution"
echo "AUTO_EXECUTION_ENABLED=0                      # Set to 1 when ready"
echo "AUTO_EXECUTION_MIN_CONFIDENCE=70              # 70% minimum"
echo "AUTO_EXECUTION_MAX_POSITIONS=5                # Max 5 concurrent"
echo "AUTO_EXECUTION_INTERVAL_S=300                 # 5 minutes"
echo "AUTO_EXECUTION_MARKET_HOURS_ONLY=1            # NYSE hours only"
echo "AUTO_EXECUTION_KELLY_FRACTION=0.25            # Quarter Kelly"
echo "AUTO_EXECUTION_MAX_POSITION_PCT=10            # 10% max per position"
echo "AUTO_EXECUTION_MIN_VOLUME_STOCKS=100000       # 100k shares min"
echo "AUTO_EXECUTION_MIN_PRICE=5.0                  # $5 minimum"
echo "AUTO_EXECUTION_MAX_DAILY_LOSS_PCT=5.0         # 5% daily loss limit"
echo "AUTO_EXECUTION_MAX_DRAWDOWN_PCT=15.0          # 15% drawdown limit"
echo ""
echo "# Enhanced SL/TP Monitor"
echo "TRAILING_STOP_ENABLED=1                       # Enable trailing stops"
echo "TRAILING_STOP_ACTIVATION_PCT=3.0              # Activate after +3%"
echo "TRAILING_STOP_DISTANCE_PCT=2.0                # Trail by 2%"
echo "PREDICTION_EXPIRY_HOURS=6.0                   # Exit after 6h"
echo "ADVERSE_MOVE_PCT=2.0                          # Exit if -2%"
echo "ADVERSE_MOVE_TIME_MINUTES=60                  # Within 1h"
echo ""
echo "# Broker (if not already set)"
echo "BROKER=alpaca"
echo "ALPACA_KEY_ID=<your_paper_key_id>"
echo "ALPACA_SECRET_KEY=<your_paper_secret_key>"
echo "ALPACA_PAPER=1                                # PAPER TRADING!"
echo ""
read -p "Press Enter when Railway variables are configured..."
echo ""

echo "📦 STEP 3: COMMIT AND PUSH TO GITHUB"
echo "------------------------------------"
echo "Commit Phase 5 files to trigger Railway deployment:"
echo ""
echo "  git add core/autonomous_execution_engine.py"
echo "  git add core/trade_decision_engine.py"
echo "  git add core/sl_tp_monitor.py"
echo "  git add core/telegram_hunter.py"
echo "  git add wolf_app.py"
echo "  git add test_autonomous_execution.py"
echo "  git commit -m 'PHASE 5 MILESTONE 1: Autonomous execution engine'"
echo "  git push origin main"
echo ""
read -p "Press Enter after pushing to GitHub..."
echo ""

echo "⏳ STEP 4: MONITOR RAILWAY DEPLOYMENT"
echo "-------------------------------------"
echo "1. Open Railway dashboard: https://railway.app"
echo "2. Watch deployment logs for:"
echo "   - ✅ Phase 4 Self-Improvement Engine active"
echo "   - 🤖 Phase 5 Autonomous Execution DISABLED"
echo "3. Check for errors in startup logs"
echo ""
echo "Expected log output:"
echo "  [GHOST STARTUP] ✅ Phase 4 Self-Improvement Engine active (hourly cycles)"
echo "  [GHOST STARTUP] 🤖 Phase 5 Autonomous Execution DISABLED (set AUTO_EXECUTION_ENABLED=1 to enable)"
echo ""
read -p "Press Enter when deployment succeeds..."
echo ""

echo "🧪 STEP 5: VALIDATE DEPLOYMENT"
echo "------------------------------"
echo "Check that Phase 5 components are loaded (but disabled):"
echo ""
echo "1. Check Railway logs for startup messages"
echo "2. Test Cockpit UI: https://your-app.railway.app"
echo "3. Verify Phase 4 is still running (hourly self-improvement)"
echo ""
read -p "Press Enter when validation is complete..."
echo ""

echo "🎯 STEP 6: ENABLE PHASE 5 (PAPER TRADING)"
echo "-----------------------------------------"
echo "⚠️  WARNING: This will enable AUTONOMOUS TRADING"
echo ""
echo "IMPORTANT:"
echo "- Paper trading only (ALPACA_PAPER=1)"
echo "- Start with small position sizes"
echo "- Monitor first 10 trades closely"
echo ""
echo "To enable:"
echo "1. Railway dashboard → Environment Variables"
echo "2. Set AUTO_EXECUTION_ENABLED=1"
echo "3. Redeploy (or wait for auto-redeploy)"
echo ""
echo "Expected behavior:"
echo "- Ghost will start placing trades every 5 minutes"
echo "- Telegram notifications for each trade"
echo "- Circuit breakers active (5% daily loss, 15% drawdown)"
echo "- Max 5 positions at once"
echo ""
read -p "Press Enter to enable Phase 5 (or Ctrl+C to cancel)..."
echo ""

echo "📊 STEP 7: MONITOR FIRST TRADES"
echo "-------------------------------"
echo "Watch the first 10 paper trades:"
echo ""
echo "1. Railway logs:"
echo "   - 🤖 [AUTO-EXECUTION] Starting execution cycle..."
echo "   - 🤖 [AUTO-EXECUTION] Cycle complete: status"
echo ""
echo "2. Telegram notifications:"
echo "   - 🔥 TRADE EXECUTED: BUY AAPL 50 @ $150.25"
echo "   - ✅ TRADE CLOSED: +$425 (5.7%)"
echo ""
echo "3. Cockpit UI:"
echo "   - Check Active Trades panel"
echo "   - Monitor P&L"
echo ""
echo "4. Alpaca dashboard:"
echo "   - https://app.alpaca.markets/"
echo "   - Verify paper trades are executing"
echo ""
echo "Monitor for:"
echo "- Trade frequency: 0-3 trades per day initially"
echo "- Win rate: 60-65% baseline"
echo "- Position sizing: 5-10% of portfolio"
echo "- Circuit breakers: Should NOT trigger under normal conditions"
echo ""
echo ""

echo "✅ DEPLOYMENT COMPLETE"
echo "======================"
echo ""
echo "Phase 5 Milestone 1 Status:"
echo "  ✅ Autonomous execution engine deployed"
echo "  ✅ Trade decision filters active"
echo "  ✅ Enhanced SL/TP monitoring"
echo "  ✅ Telegram notifications"
echo "  ✅ Circuit breakers armed"
echo ""
echo "Next Steps:"
echo "  1. Monitor first 10-20 paper trades"
echo "  2. Validate win rate: 60-65%"
echo "  3. Check circuit breakers (should not trigger)"
echo "  4. Review Telegram notifications"
echo "  5. Proceed to Milestone 2 (Post-Trade Learning)"
echo ""
echo "Emergency Controls:"
echo "  - Pause trading: Set AUTO_EXECUTION_ENABLED=0"
echo "  - Circuit breaker: Triggers at 5% daily loss or 15% drawdown"
echo "  - Manual intervention: Use Alpaca dashboard to close positions"
echo ""
echo "🎉 Ghost is now autonomous!"
echo ""
