#!/bin/bash
# Quick deploy script for the cleanup endpoint fix

echo "📦 Deployment Instructions for Cleanup Endpoint Fix"
echo "===================================================="
echo ""
echo "🔧 ISSUE FIXED:"
echo "   - Type casting error: created_at column comparison"
echo "   - Changed from timestamp to string comparison"
echo ""
echo "🚀 TO DEPLOY FROM YOUR MAC:"
echo ""
echo "cd ~/ghost-protocol"
echo "git pull  # Get latest changes from container"
echo "git add wolf_app.py"
echo "git commit -m 'Fix type casting in cleanup endpoint - use string comparison for created_at'"
echo "git push origin main"
echo ""
echo "⏱️  Wait 2-3 minutes for Railway deployment"
echo ""
echo "✅ THEN TEST:"
echo ""
echo "# Dry run (safe, no changes)"
echo "curl -X POST 'https://ghost-protocol-production.up.railway.app/api/v3/paper/admin/expire-old-pending?dry_run=true&cutoff_date=2026-01-14'"
echo ""
echo "# Execute (for real)"  
echo "curl -X POST 'https://ghost-protocol-production.up.railway.app/api/v3/paper/admin/expire-old-pending?cutoff_date=2026-01-14'"
echo ""
