#!/bin/bash
# Ghost Protocol - Deploy Honest Fixes to Railway
# =================================================
# Date: January 7, 2026
# Changes: Removed all hacks, fixed look-ahead bias

echo "🔧 DEPLOYING HONEST FIXES TO RAILWAY"
echo "======================================"
echo ""

# Step 1: Remove INVERSE_GHOST variable
echo "📋 Step 1: Remove INVERSE_GHOST from Railway"
echo ""
echo "   1. Go to: https://railway.app/project/YOUR_PROJECT_ID/service/YOUR_SERVICE_ID"
echo "   2. Click 'Variables' tab"
echo "   3. Find 'INVERSE_GHOST' variable"
echo "   4. Click '...' → Delete"
echo "   5. Click 'Deploy'"
echo ""
echo "   ⚠️  IMPORTANT: Delete INVERSE_GHOST=1 variable"
echo "   (Hack removed, model predictions are now raw/honest)"
echo ""
read -p "Press Enter when INVERSE_GHOST is deleted..."

# Step 2: Force redeploy (Railway auto-deploys on git push)
echo ""
echo "📦 Step 2: Railway Auto-Deploy"
echo ""
echo "   ✅ Code pushed to GitHub (commit e871f71)"
echo "   ⏳ Railway will auto-deploy in 2-3 minutes"
echo "   🔗 Check: https://railway.app/project/YOUR_PROJECT_ID/deployments"
echo ""

# Step 3: Verify deployment
echo "📊 Step 3: Verify Deployment"
echo ""
echo "   Run these commands in 5 minutes (after deploy completes):"
echo ""
echo "   # Check if INVERSE_GHOST is gone"
echo "   railway run python3 -c \"import os; print('INVERSE_GHOST =', os.getenv('INVERSE_GHOST', 'NOT SET'))\""
echo ""
echo "   # Should output: INVERSE_GHOST = NOT SET"
echo ""

# Step 4: Test predictions
echo "🧪 Step 4: Test Predictions"
echo ""
echo "   # Force a prediction to test (wait for market open/close)"
echo "   # Check logs for:"
echo "   railway logs | tail -50"
echo ""
echo "   # Look for:"
echo "   # ✅ '🤖 XGBoost v2 for BTC: UP=62%, DOWN=38%' (raw output, no calibration)"
echo "   # ❌ NO '[INVERSE_GHOST] Flipping' messages"
echo "   # ❌ NO 'Calibrated=' messages (compression removed)"
echo ""

# Step 5: Monitor accuracy
echo "📈 Step 5: Monitor Real Accuracy (24-48 hours)"
echo ""
echo "   # Check accuracy after 100+ predictions"
echo "   railway run python3 -c \""
echo "   from core.learning_loop import get_learning_loop"
echo "   ll = get_learning_loop()"
echo "   result = ll._get_postgres_direction_accuracy(days=1)"
echo "   print(f'Accuracy: {result[\"accuracy_pct\"]:.1f}%')"
echo "   print(f'Total: {result[\"count\"]} predictions')"
echo "   \""
echo ""
echo "   # Expected: 35-58% (real performance, no hacks)"
echo "   # If 35%: Model is still anti-correlated → Need retrain"
echo "   # If 50%: Model is coin flip → Need retrain"
echo "   # If 55%+: Model is working! → Can improve with retrain"
echo ""

# Step 6: Retrain model (if needed)
echo "🎓 Step 6: Retrain Model (48-72 hours from now)"
echo ""
echo "   # Wait for 500+ outcomes to accumulate"
echo "   railway run python3 -c \""
echo "   import psycopg2, os"
echo "   conn = psycopg2.connect(os.getenv('DATABASE_URL'))"
echo "   cur = conn.cursor()"
echo "   cur.execute('SELECT COUNT(*) FROM ghost_prediction_outcomes WHERE status = \\'closed\\')')"
echo "   print(f'Outcomes: {cur.fetchone()[0]}')"
echo "   \""
echo ""
echo "   # If 500+ outcomes exist, retrain:"
echo "   railway run python3 -c \""
echo "   from core.ml_trainer import train_model"
echo "   result = train_model(symbol=None, lookback_days=180, min_samples=500)"
echo "   print(f'New Model: {result[\"test_accuracy\"]:.1%} accuracy')"
echo "   print(f'Samples: {result[\"samples\"]}')"
echo "   \""
echo ""
echo "   # Expected: 55-65% realistic accuracy (no look-ahead bias)"
echo ""

# Done
echo "✅ DEPLOYMENT COMPLETE"
echo "======================"
echo ""
echo "Summary:"
echo "  ✅ Removed INVERSE_GHOST flip hack"
echo "  ✅ Removed +16% UP bias correction"
echo "  ✅ Removed probability compression"
echo "  ✅ Fixed look-ahead bias in training"
echo "  ✅ Model predictions now RAW/HONEST"
echo ""
echo "Next Steps:"
echo "  1. ⏳ Wait 24h for 100+ predictions"
echo "  2. 📊 Check real accuracy (expect 35-58%)"
echo "  3. 🎓 Retrain model on PostgreSQL (48-72h)"
echo "  4. 🎯 Target: 60-70% natural accuracy"
echo ""
echo "Status: Ghost is HONEST now (7/10), will be FIXED after retrain (9/10)"
echo ""
