# Auto-generated by auto_calibrate.py
# Generated: 2026-02-05 16:16:26

V3_VALIDATED_STRATEGIES = {
    # STOCKS
    'DDOG': {
        'strategy': 'always_up',
        'direction_override': None,
        'hold_hours': 48,
        'win_rate': 0.569,
        'sample_size': 202,
        'p_value': 0.0286,
        'asset_type': 'stock',
    },
    'FTNT': {
        'strategy': 'ghost_inverse',
        'direction_override': 'flip',
        'hold_hours': 168,
        'win_rate': 0.623,
        'sample_size': 69,
        'p_value': 0.0266,
        'asset_type': 'stock',
    },
    'NET': {
        'strategy': 'ghost_inverse',
        'direction_override': 'flip',
        'hold_hours': 168,
        'win_rate': 0.625,
        'sample_size': 72,
        'p_value': 0.0222,
        'asset_type': 'stock',
    },
    'PANW': {
        'strategy': 'ghost_inverse',
        'direction_override': 'flip',
        'hold_hours': 168,
        'win_rate': 0.646,
        'sample_size': 65,
        'p_value': 0.0124,
        'asset_type': 'stock',
    },
    'SNOW': {
        'strategy': 'random',
        'direction_override': None,
        'hold_hours': 24,
        'win_rate': 0.586,
        'sample_size': 203,
        'p_value': 0.0084,
        'asset_type': 'stock',
    },
}